[env:uno]
platform = atmelavr
board = uno
framework = arduino

build_flags = 
    -I include

[env:native]
platform = native
 
build_flags =
    -I include
    -I lib/pid
    -I lib/sensors
    -I lib/engine
    -D UNIT_TEST
    -std=c++17